### ISSUE TITLE
Unicode support of MZBench.

### ISSUE THREAD

**Issue by loguntsov** [machinezone/mzbench#81] opened 2016-10-24 19:37 UTC
I tried use mzbench on my local machine (ubuntu 14.04, Russian language of console, erlang 18).
So i got error message in log of benchmark:

`
22:14:18.678 [error] <0.180.0> Error parsing network info: {parse_netstat_output_error,badarg,[1058,1072,1073,1083,1080,1094,1072,32,1080,1085,1090,1077,1088,1092,1077,1081,1089,1086,1074,32,1103,1076,1088,1072,10,100,111,99,107,101,114,48,32,32,32,76,105,110,107,32,101,110,99,97,112,58,69,116,104,101,114,110,101,116,32,32,72,87,97,100,100,114,32,53,54,58,56,52,58,55,97,58,102,101,58,57,55,58,57,57,32,32,10,32,32,32,32,32,32,32,32,32,32,105,110,101,116,32,97,100,100,114,58,49,55,50,46,49,55,46,52,50,46,49,32,32,66,99,97,115,116,58,48,46,48,46,48,46,48,32,32,77,97,115,107,58,50,53,53,46,50,53,53,46,48,46,48,10,32,32,32,32,32,32,32,32,32,32,85,80,32,66,82,79,65,68,67,65,83,84,32,77,85,76,84,73,67,65,83,84,32,32,77,84,85,58,49,53,48,48,32,32,77,101,116,114,105,99,58,49,10,32,32,32,32,32,32,32,32,32,32,82,88,32,112,97,99,107,101,116,115,58,48,32,101,114,114,111,114,115,58,48,32,100,114,111,112,112,101,100,58,48,32,111,118,101,114,114,117,110,115,58,48,32,102,114,97,109,101,58,48,10,32,32,32,32,32,32,32,32,32,32,84,88,32,112,97,99,107,101,116,115,58,48,32,101,114,114,111,114,115,58,48,32,100,114,111,112,112,101,100,58,48,32,111,118,101,114,114,117,110,115,58,48,32,99,97,114,114,105,101,114,58,48,10,32,32,32,32,32,32,32,32,32,32,99,111,108,108,105,115,105,111,110,115,58,48,32,116,120,113,117,101,117,101,108,101,110,58,48,32,10,32,32,32,32,32,32,32,32,32,32,82,88,32,98,121,116,101,115,58,48,32,40,48,46,48,32,66,41,32,32,84,88,32,98,121,116,101,115,58,48,32,40,48,46,48,32,66,41,10,10,101,116,104,48,32,32,32,32,32,32,76,105,110,107,32,101,110,99,97,112,58,69,116,104,101,114,110,101,116,32,32,72,87,97,100,100,114,32,99,56,58,54,48,58,48,48,58,55,51,58,51,49,58,52,49,32,32,10,32,32,32,32,32,32,32,32,32,32,105,110,101,116,32,97,100,100,114,58,49,57,50,46,49,54,56,46,49,46,51,32,32,66,99,97,115,116,58,49,57,50,46,49,54,56,46,50,53,53,46,50,53,53,32,32,77,97,115,107,58,50,53,53,46,50,53,53,46,48,46,48,10,32,32,32,32,32,32,32,32,32,32,105,110,101,116,54,32,97,100,100,114,58,32,102,101,56,48,58,58,99,97,54,48,58,102,102,58,102,101,55,51,58,51,49,52,49,47,54,52,32,83,99,111,112,101,58,76,105,110,107,10,32,32,32,32,32,32,32,32,32,32,85,80,32,66,82,79,65,68,67,65,83,84,32,82,85,78,78,73,78,71,32,77,85,76,84,73,67,65,83,84,32,32,77,84,85,58,49,53,48,48,32,32,77,101,116,114,105,99,58,49,10,32,32,32,32,32,32,32,32,32,32,82,88,32,112,97,99,107,101,116,115,58,49,57,57,56,52,48,53,55,32,101,114,114,111,114,115,58,48,32,100,114,111,112,112,101,100,58,48,32,111,118,101,114,114,117,110,115,58,48,32,102,114,97,109,101,58,48,10,32,32,32,32,32,32,32,32,32,32,84,88,32,112,97,99,107,101,116,115,58,49,57,54,51,52,57,52,48,32,101,114,114,111,114,115,58,48,32,100,114,111,112,112,101,100,58,48,32,111,118,101,114,114,117,110,115,58,48,32,99,97,114,114,105,101,114,58,48,10,32,32,32,32,32,32,32,32,32,32,99,111,108,108,105,115,105,111,110,115,58,48,32,116,120,113,117,101,117,101,108,101,110,58,49,48,48,48,32,10,32,32,32,32,32,32,32,32,32,32,82,88,32,98,121,116,101,115,58,50,48,57,55,48,52,52,57,52,57,54,32,40,50,48,46,57,32,71,66,41,32,32,84,88,32,98,121,116,101,115,58,49,53,48,54,56,51,51,49,48,50,56,32,40,49,53,46,48,32,71,66,41,10,32,32,32,32,32,32,32,32,32,32,73,110,116,101,114,114,117,112,116,58,50,48,32,1055,1072,1084,1103,1090,1100,58,102,55,102,48,48,48,48,48,45,102,55,102,50,48,48,48,48,32,10,10,108,111,32,32,32,32,32,32,32,32,76,105,110,107,32,101,110,99,97,112,58,1051,1086,1082,1072,1083,1100,1085,1072,1103,32,1087,1077,1090,1083,1103,32,40,76,111,111,112,98,97,99,107,41,32,32,10,32,32,32,32,32,32,32,32,32,32,105,110,101,116,32,97,100,100,114,58,49,50,55,46,48,46,48,46,49,32,32,77,97,115,107,58,50,53,53,46,48,46,48,46,48,10,32,32,32,32,32,32,32,32,32,32,105,110,101,116,54,32,97,100,100,114,58,32,58,58,49,47,49,50,56,32,83,99,111,112,101,58,72,111,115,116,10,32,32,32,32,32,32,32,32,32,32,85,80,32,76,79,79,80,66,65,67,75,32,82,85,78,78,73,78,71,32,32,77,84,85,58,54,53,53,51,54,32,32,77,101,116,114,105,99,58,49,10,32,32,32,32,32,32,32,32,32,32,82,88,32,112,97,99,107,101,116,115,58,53,50,53,51,55,56,32,101,114,114,111,114,115,58,48,32,100,114,111,112,112,...] 
`

Seems mzbench running without support of unicode, because this list is strings of russian letters in unicode.

`
begemot@big-comp:~$ erl +pc unicode
Erlang/OTP 18 [erts-7.3] [source-d2a6d81] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.3  (abort with ^G)
1> A = [ 1058,1072,1073,1083,1080,1094,1072,32,1080,1085,1090,1077,1088,1092,1077,1081,1089,1086,1074,32,1103,1076,1088,1072,10,100,111,99,107,101,114,48,32,32,32,76,105,110,107,32,101,110,99,97,112,58,69,116,104,101,114,110,101,116,32,32,72,87,97,100,100,114,32,53,54,58,56,52,58,55,97,58,102,101,58,57,55,58,57,57,32,32,10,32,32,32,32,32,32,32,32,32,32,105,110,101,116,32,97,100,100,114,58,49,55,50,46,49,55,46,52,50,46,49,32,32,66,99,97,115,116,58,48,46,48,46,48,46,48,32,32,77,97,115,107,58,50,53,53,46,50,53,53,46,48,46,48,10,32,32,32,32,32,32,32,32,32,32,85,80,32,66,82,79,65,68,67,65,83,84,32,77,85,76,84,73,67,65,83,84,32,32,77,84,85,58,49,53,48,48,32,32,77,101,116,114,105,99,58,49,10,32,32,32,32,32,32,32,32,32,32,82,88,32,112,97,99,107,101,116,115,58,48,32,101,114,114,111,114,115,58,48,32,100,114,111,112,112,101,100,58,48,32,111,118,101,114,114,117,110,115,58,48,32,102,114,97,109,101,58,48,10,32,32,32,32,32,32,32,32,32,32,84,88,32,112,97,99,107,101,116,115,58,48,32,101,114,114,111,114,115,58,48,32,100,114,111,112,112,101,100,58,48,32,111,118,101,114,114,117,110,115,58,48,32,99,97,114,114,105,101,114,58,48,10,32,32,32,32,32,32,32,32,32,32,99,111,108,108,105,115,105,111,110,115,58,48,32,116,120,113,117,101,117,101,108,101,110,58,48,32,10,32,32,32,32,32,32,32,32,32,32,82,88,32,98,121,116,101,115,58,48,32,40,48,46,48,32,66,41,32,32,84,88,32,98,121,116,101,115,58,48,32,40,48,46,48,32,66,41,10,10,101,116,104,48,32,32,32,32,32,32,76,105,110,107,32,101,110,99,97,112,58,69,116,104,101,114,110,101,116,32,32,72,87,97,100,100,114,32,99,56,58,54,48,58,48,48,58,55,51,58,51,49,58,52,49,32,32,10,32,32,32,32,32,32,32,32,32,32,105,110,101,116,32,97,100,100,114,58,49,57,50,46,49,54,56,46,49,46,51,32,32,66,99,97,115,116,58,49,57,50,46,49,54,56,46,50,53,53,46,50,53,53,32,32,77,97,115,107,58,50,53,53,46,50,53,53,46,48,46,48,10,32,32,32,32,32,32,32,32,32,32,105,110,101,116,54,32,97,100,100,114,58,32,102,101,56,48,58,58,99,97,54,48,58,102,102,58,102,101,55,51,58,51,49,52,49,47,54,52,32,83,99,111,112,101,58,76,105,110,107,10,32,32,32,32,32,32,32,32,32,32,85,80,32,66,82,79,65,68,67,65,83,84,32,82,85,78,78,73,78,71,32,77,85,76,84,73,67,65,83,84,32,32,77,84,85,58,49,53,48,48,32,32,77,101,116,114,105,99,58,49,10,32,32,32,32,32,32,32,32,32,32,82,88,32,112,97,99,107,101,116,115,58,49,57,57,57,55,50,56,51,32,101,114,114,111,114,115,58,48,32,100,114,111,112,112,101,100,58,48,32,111,118,101,114,114,117,110,115,58,48,32,102,114,97,109,101,58,48,10,32,32,32,32,32,32,32,32,32,32,84,88,32,112,97,99,107,101,116,115,58,49,57,54,52,54,49,51,48,32,101,114,114,111,114,115,58,48,32,100,114,111,112,112,101,100,58,48,32,111,118,101,114,114,117,110,115,58,48,32,99,97,114,114,105,101,114,58,48,10,32,32,32,32,32,32,32,32,32,32,99,111,108,108,105,115,105,111,110,115,58,48,32,116,120,113,117,101,117,101,108,101,110,58,49,48,48,48,32,10,32,32,32,32,32,32,32,32,32,32,82,88,32,98,121,116,101,115,58,50,48,57,55,55,56,48,54,52,53,57,32,40,50,48,46,57,32,71,66,41,32,32,84,88,32,98,121,116,101,115,58,49,53,48,54,57,54,53,57,55,53,53,32,40,49,53,46,48,32,71,66,41,10,32,32,32,32,32,32,32,32,32,32,73,110,116,101,114,114,117,112,116,58,50,48,32,1055,1072,1084,1103,1090,1100,58,102,55,102,48,48,48,48,48,45,102,55,102,50,48,48,48,48,32,10,10,108,111,32,32,32,32,32,32,32,32,76,105,110,107,32,101,110,99,97,112,58,1051,1086,1082,1072,1083,1100,1085,1072,1103,32,1087,1077,1090,1083,1103,32,40,76,111,111,112,98,97,99,107,41,32,32,10,32,32,32,32,32,32,32,32,32,32,105,110,101,116,32,97,100,100,114,58,49,50,55,46,48,46,48,46,49,32,32,77,97,115,107,58,50,53,53,46,48,46,48,46,48,10,32,32,32,32,32,32,32,32,32,32,105,110,101,116,54,32,97,100,100,114,58,32,58,58,49,47,49,50,56,32,83,99,111,112,101,58,72,111,115,116,10,32,32,32,32,32,32,32,32,32,32,85,80,32,76,79,79,80,66,65,67,75,32,82,85,78,78,73,78,71,32,32,77,84,85,58,54,53,53,51,54,32,32,77,101,116,114,105,99,58,49,10,32,32,32,32,32,32,32,32,32,32,82,88,32,112,97,99,107,101,116,115,58,53,51,48,50,49,52,32,101,114,114,111,114,115,58,48,32,100,114,111,112,112 ].
            .
"Таблица интерфейсов ядра\ndocker0   Link encap:Ethernet  HWaddr 56:84:7a:fe:97:99  \n          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0\n          UP BROADCAST MULTICAST  MTU:1500  Metric:1\n          RX packets:0 errors:0 dropped:0 overruns:0 frame:0\n          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0\n          collisions:0 txqueuelen:0 \n          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)\n\neth0      Link encap:Ethernet  HWaddr c8:60:00:73:31:41  \n          inet addr:192.168.1.3  Bcast:192.168.255.255  Mask:255.255.0.0\n          inet6 addr: fe80::ca60:ff:fe73:3141/64 Scope:Link\n          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1\n          RX packets:19997283 errors:0 dropped:0 overruns:0 frame:0\n          TX packets:19646130 errors:0 dropped:0 overruns:0 carrier:0\n          collisions:0 txqueuelen:1000 \n          RX bytes:20977806459 (20.9 GB)  TX bytes:15069659755 (15.0 GB)\n          Interrupt:20 Память:f7f00000-f7f20000 \n\nlo        Link encap:Локальная петля (Loopback)  \n          inet addr:127.0.0.1  Mask:255.0.0.0\n          inet6 addr: ::1/128 Scope:Host\n          UP LOOPBACK RUNNING  MTU:65536  Metric:1\n          RX packets:530214 errors:0 dropp"
`

**Comment by parsifal-47** [comment] 2016-10-26 14:50
Hi Sergey,
thanks for reporting this, but it is not about unicode itself. For example, you could name your benchmarking scenario with Cyrillic letters and it should be fine. In this case, the problem is netstat output. As you can see here:

https://github.com/machinezone/mzbench/blob/master/node/apps/mzbench/src/mzb_system_load_monitor.erl

we parse outputs for different systems and limited to english-only versions. Of course, it is better to have more general solution for network monitoring, but we don't have any

**Comment by loguntsov** [comment] 2016-10-27 08:37
With this patch https://github.com/loguntsov/mzbench/commit/03264e685e427e4f3f0138f98682df34bccf4184
it works fine for me.

**Comment by parsifal-47** [comment] 2016-10-27 11:01
thank you,
merged to master

**Comment by parsifal-47** [comment] 2016-10-28 09:07
same comment, feel free to re-open

**Closed by parsifal-47** 2016-10-28 09:07 UTC
